kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 9999 #can be any number
    targetPort: 8080 #container port and target port usually be same

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: nagadheeraj/train_image:tagVersion #tagVersion will be changed from the bash script
        ports:
        - containerPort: 8080  #containerPort is the port of NodeJs app default port